"""Report branding: preset/registered/path logo selection + the always-on footer."""

from __future__ import annotations

from pathlib import Path

import pytest

from exa.report import brand as brandmod
from exa.report.brand import BrandError, resolve_logo
from exa.report.build import report_from_spec
from exa.report.theme import page

_PKG = Path(brandmod.__file__).resolve().parent


def _b64(name: str) -> str:
    return (_PKG / name).read_text(encoding="utf-8").strip()


EXABEAM_DARK = _b64("_logo_dark_b64.txt")
EXATOOLS_DARK = _b64("_logo_exatools_dark_b64.txt")

# A tiny valid 1x1 PNG for path/registry tests.
_PNG_1x1 = bytes.fromhex(
    "89504e470d0a1a0a0000000d4948445200000001000000010806000000"
    "1f15c4890000000d49444154789c6360000002000155bf9e8d0000000049454e44ae426082"
)


@pytest.fixture
def brand_dir(monkeypatch, tmp_path):
    d = tmp_path / "brand"
    monkeypatch.setattr(brandmod, "_BRAND_DIR", d)
    return d


# --- presets ----------------------------------------------------------------


def test_default_is_exabeam():
    logo = resolve_logo()
    assert logo.alt == "Exabeam"
    assert EXABEAM_DARK in logo.dark_src
    assert logo.dark_src.startswith("data:image/svg+xml;base64,")


def test_exatools_preset_swaps_only_the_logo():
    logo = resolve_logo("exa-tools")
    assert logo.alt == "exa-tools"
    assert EXATOOLS_DARK in logo.dark_src
    assert EXABEAM_DARK not in logo.dark_src


def test_default_page_has_exabeam_logo_and_footer():
    html = page("Q report")
    assert EXABEAM_DARK in html
    assert "Generated by <b>exa-tools</b>" in html
    assert 'alt="Exabeam"' in html


def test_exatools_page_uses_exatools_logo():
    html = page("Internal report", brand="exa-tools")
    assert EXATOOLS_DARK in html
    assert EXABEAM_DARK not in html


def test_footer_can_be_disabled():
    html = page("Customer deliverable", footer_brand=False)
    assert "Generated by <b>exa-tools</b>" not in html
    # ...but the Exabeam header logo is still there.
    assert EXABEAM_DARK in html


def test_report_is_self_contained():
    html = page("R", brand="exa-tools")
    assert 'src="http' not in html and "src='http" not in html


# --- registry ---------------------------------------------------------------


def test_register_and_resolve_custom_logo(brand_dir):
    logo_file = brand_dir.parent / "acme.png"
    logo_file.write_bytes(_PNG_1x1)
    brandmod.add_brand("acme", logo_file)
    assert brandmod.list_brands() == ["acme"]
    logo = resolve_logo("acme")
    assert logo.alt == "acme"
    assert logo.dark_src.startswith("data:image/png;base64,")


def test_register_light_variant(brand_dir):
    dark = brand_dir.parent / "acme.png"
    light = brand_dir.parent / "acme-l.png"
    dark.write_bytes(_PNG_1x1)
    light.write_bytes(_PNG_1x1)
    brandmod.add_brand("acme", dark, light)
    logo = resolve_logo("acme")
    assert logo.dark_src.startswith("data:image/png")
    assert logo.light_src.startswith("data:image/png")


def test_cannot_shadow_or_remove_preset(brand_dir):
    src = brand_dir.parent / "x.png"
    src.write_bytes(_PNG_1x1)
    with pytest.raises(BrandError):
        brandmod.add_brand("exabeam", src)
    with pytest.raises(BrandError):
        brandmod.remove_brand("exa-tools")


def test_remove_brand(brand_dir):
    src = brand_dir.parent / "acme.png"
    src.write_bytes(_PNG_1x1)
    brandmod.add_brand("acme", src)
    assert brandmod.remove_brand("acme") == 1
    assert brandmod.list_brands() == []


def test_unknown_brand_raises(brand_dir):
    with pytest.raises(BrandError):
        resolve_logo("does-not-exist")


def test_oversized_logo_rejected(brand_dir):
    big = brand_dir.parent / "big.png"
    big.write_bytes(b"\x89PNG" + b"\x00" * (3 * 1024 * 1024))
    with pytest.raises(BrandError):
        brandmod.add_brand("big", big)


def test_path_brand_embeds_file(tmp_path):
    p = tmp_path / "oneoff.png"
    p.write_bytes(_PNG_1x1)
    logo = resolve_logo(str(p))
    assert logo.dark_src.startswith("data:image/png;base64,")
    assert logo.alt == "oneoff"


# --- spec passthrough -------------------------------------------------------


def test_spec_threads_brand_and_footer():
    exa = report_from_spec({"title": "T", "brand": "exa-tools"})
    assert EXATOOLS_DARK in exa
    off = report_from_spec({"title": "T", "footer_brand": False})
    assert "Generated by <b>exa-tools</b>" not in off
    default = report_from_spec({"title": "T"})
    assert EXABEAM_DARK in default and "Generated by <b>exa-tools</b>" in default
