"""Gap analysis — what the tenant emits that the AI/LLM context tables lack.

``exa aillm validate`` answers ``table ∩ live``. That tells you a table is dead;
it never tells you what to put in it. This module answers the other direction,
``live − table``, and then does the part that actually takes judgement: deciding
which of those values may be added and which must not.

This command is READ-ONLY. It writes a reviewable JSON file and nothing else.

Why classification, and not just a diff
---------------------------------------
A raw diff on a live healthcare tenant returned **27,167** missing ``alert_name``
values over 30 days. Adding them would have been catastrophic and would have
looked like progress:

- **19,134** were Microsoft Purview classic DLP matches, each carrying the
  matched EMAIL SUBJECT — one distinct value per email, patient content in the
  string, and no exact-match context table can ever match them. Stripped of the
  vendor wrapper they collapse to **2** policy names.
- **7,276** were Check Point machine-generated tokens (``dga-Cai8Z.TC.893fEDbW``)
  that never recur.
- **749** were ordinary security alerts with no AI relevance at all.

**8** were genuine AI alert names. That ratio is the reason every value gets an
explicit decision and a machine-readable reason, and why nothing is ever
silently dropped: the count of examined values equals the count accounted for
in the two buckets, and the report asserts it.

What is written to disk
-----------------------
Alert names are free text authored by the source product, and on this class of
tenant they carry patient and provider names. So:

- ``propose`` values are always written — they are vetted by construction: AI
  classified, and rejected outright if they carry a per-record shape (an email
  subject, an address, or simply an implausible length for a policy name).
- ``high-cardinality-per-record`` withholds write only the NORMALISED value
  recovered by the vendor pack (the policy name), never the raw string. With no
  pack to normalise with, the value is redacted and only the count survives.
- ``machine-generated`` withholds write the value: matching a vendor's own noise
  regex proves the string was generated by the product, not typed by a person.
- every other withheld ``alert_name`` value is redacted unless the operator
  passes ``--include-withheld-values``. Counts and vendor attribution are always
  reported, which is what a reviewer needs.
- domains, categories, apps and process names are structured vendor taxonomies
  rather than free text, and are always written — they are the reviewable
  output of this command.

Counts are LOWER BOUNDS whenever the underlying profile sample was truncated.
The 5,000-value enumeration caps out on any busy tenant and is not deterministic
between runs, so "not found" never means "not present".
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

from exa.aillm.discover import (
    CANDIDATE,
    EXCLUDED,
    KNOWN,
    discover_ai_domains,
    discover_categories,
    has_ai_provider_token,
    has_weak_ai_hint,
    is_ai_alert_name,
)
from exa.aillm.profile import (
    FieldValues,
    TenantProfile,
    collect_tenant_profile,
    ensure_fields,
    save_profile,
)
from exa.aillm.validate import TABLE_SPECS, TableValidation, validate_aillm_tables
from exa.aillm.vendors import (
    Normalised,
    VendorPack,
    known_ai_categories,
    load_vendor_packs,
    match_pack,
    normalise_alert_names,
)

if TYPE_CHECKING:
    from exa.client import ExaClient

PROPOSE = "propose"
WITHHOLD = "withhold"

# Withhold reasons. Machine-readable on purpose: `exa aillm gaps apply` filters
# on these, and a human-readable sentence is not a filter.
REASON_HIGH_CARDINALITY = "high-cardinality-per-record"
REASON_MACHINE_GENERATED = "machine-generated"
REASON_NOT_AI = "not-ai-related"
REASON_EXCLUDED_MARTECH = "excluded-martech"
REASON_NEEDS_REVIEW = "needs-review"
REASON_ALREADY_COVERED = "covered-after-normalisation"

# Propose reasons — why this value is safe to add.
REASON_REFERENCE = "matched-reference-data"
REASON_AI_CLASSIFIED = "ai-classified"
REASON_AI_CATEGORY = "ai-category"
REASON_VENDOR_CATEGORY = "vendor-pack-category"
REASON_VENDOR_TEMPLATE = "vendor-pack-template"
REASON_AI_POLICY = "ai-policy-normalised"
REASON_AI_OVER_NOISE = "ai-signal-over-vendor-noise"
REASON_AI_PROCESS = "ai-runtime-process"

WITHHOLD_REASONS = (
    REASON_HIGH_CARDINALITY,
    REASON_MACHINE_GENERATED,
    REASON_NOT_AI,
    REASON_EXCLUDED_MARTECH,
    REASON_NEEDS_REVIEW,
    REASON_ALREADY_COVERED,
)

# A vendor noise pattern is only overridden by an AI signal that survives word
# boundaries. The shared classifier matches "LLM" anywhere, which is correct for
# ordinary alert names and wrong for base62 noise: Check Point emitted
# `dga-6WsNw.TC.c5b8LLMs` and `dga-3pQD2.TC.70e8uLlM` on a live tenant, and a
# substring match would have proposed random DGA tokens as AI alert names.
_STRONG_AI = re.compile(
    r"\bAI\b|(?-i:\bAI(?=[A-Z][a-z]))|\bLLM\b|\bGenAI\b|\bcopilot\b|\bchatbot\b|"
    r"\bgenerative\b|\bprompt\b|DSPM for AI",
    re.I,
)

# Row cap for a re-enumeration of a field the standing profile truncated. The
# standing 5,000 cap is not a sane sample: it is 5,000 arbitrary values out of
# 27,781, and on a live tenant it hid six of the eight genuine AI alert names
# behind Purview per-email noise. There is no 3,000-row API limit; 50,000 works.
_DEEP_LIMIT = 50_000

# Shapes that mean "this string was built per event, not per policy". Anything
# matching is never proposed, and its raw text never reaches disk.
_PER_RECORD = re.compile(
    r"matched for .{0,40}with subject|subject \(|[\w.+-]+@[\w-]+\.[a-z]{2,}", re.I
)
# A context-table entry is a policy/category/app name. Nothing legitimate in
# that role runs long; length alone is a reliable per-record tell.
_MAX_ENTRY_CHARS = 120

# Locally-run model runtimes and AI dev tooling. These leave no network trace
# after the initial download, so process telemetry is the only place they show
# up at all (AI Agent / AI Dev Framework Process Names, 6 rules each).
_AI_PROCESS = re.compile(
    r"ollama|lm[ _-]?studio|llama[._-]?cpp|llamafile|gpt4all|jan\.exe|msty|"
    r"anythingllm|localai|open[-_]?webui|text-generation-webui|koboldcpp|vllm|"
    r"comfyui|automatic1111|claude|cursor|copilot|continue|aider|goose|"
    r"mcp[-_]server|langchain|autogen|crewai",
    re.I,
)
# Interpreters and package managers. They RUN the frameworks above, so they are
# genuinely relevant — and they are also half of every enterprise's endpoint
# fleet. Proposing python.exe into a table six rules read would fire those rules
# on everything. Review, never auto-add.
_DEV_PROCESS = re.compile(
    r"^(python[\d.]*|pythonw|node|npm|npx|yarn|pnpm|uv|uvx|pip[\d.]*|conda|"
    r"deno|bun|ruby|perl|java)(\.exe)?$",
    re.I,
)

# Which classifier a table's fields call for.
_KIND_BY_FIELD: dict[str, str] = {
    "web_domain": "domain",
    "category": "category",
    "categories": "category",
    "alert_name": "alert_name",
    "app": "app",
    "process_name": "process",
    "parent_process_name": "process",
}


@dataclass
class GapValue:
    """One decision, covering ``raw_count`` live values that reduced to it."""

    value: str | None
    table: str
    field_name: str
    decision: str
    reason: str
    raw_count: int = 1
    normalised: bool = False
    redacted: bool = False
    sources: list[str] = field(default_factory=list)
    detail: str = ""

    @property
    def is_proposal(self) -> bool:
        return self.decision == PROPOSE


@dataclass
class TableGaps:
    """Every missing value for one context table, classified."""

    table_name: str
    fields: list[str] = field(default_factory=list)
    table_id: str | None = None
    key_attr: str = "key"
    status: str = ""
    records: int = 0
    consumers: list[str] = field(default_factory=list)
    read_by_rules: bool = False
    truncated_sample: bool = False
    note: str = ""
    # Live values examined for this table (i.e. len(TableValidation.missing)).
    examined: int = 0
    propose: list[GapValue] = field(default_factory=list)
    withhold: list[GapValue] = field(default_factory=list)

    @property
    def proposed(self) -> int:
        """Distinct values proposed. Never a lower bound on its own — see note."""
        return len(self.propose)

    @property
    def withheld_values(self) -> int:
        """Live values withheld, counted BEFORE normalisation collapsed them."""
        return sum(g.raw_count for g in self.withhold)

    @property
    def withheld_distinct(self) -> int:
        """Withheld entries after normalisation — 3,573 Purview values give 2."""
        return len(self.withhold)

    @property
    def accounted(self) -> int:
        return sum(g.raw_count for g in self.propose + self.withhold)

    @property
    def balanced(self) -> bool:
        """Every examined value landed in exactly one bucket."""
        return self.accounted == self.examined

    def by_reason(self) -> dict[str, int]:
        out: dict[str, int] = {}
        for g in self.withhold:
            out[g.reason] = out.get(g.reason, 0) + g.raw_count
        return dict(sorted(out.items(), key=lambda kv: (-kv[1], kv[0])))


@dataclass
class GapReport:
    """Gap analysis across every AI/LLM context table."""

    tenant: str
    collected_at: str
    lookback_days: int = 30
    api_calls: int = 0
    truncated_fields: list[str] = field(default_factory=list)
    # Fields re-enumerated at a higher row cap because the standing sample was
    # capped. Recorded so a reader can tell a complete answer from a sampled one.
    deepened_fields: list[str] = field(default_factory=list)
    tables: list[TableGaps] = field(default_factory=list)

    @property
    def lower_bound(self) -> bool:
        """True when at least one sample was truncated — no count is complete."""
        return bool(self.truncated_fields)

    @property
    def total_proposed(self) -> int:
        return sum(t.proposed for t in self.tables)

    @property
    def balanced(self) -> bool:
        return all(t.balanced for t in self.tables)


# --- helpers -----------------------------------------------------------------


def _sources(profile: TenantProfile, fields: list[str], value: str) -> list[str]:
    """Vendor/product attributions for a value, across every field it may sit in."""
    out: set[str] = set()
    for f in fields:
        out.update(profile.sources_for(f, value))
    return sorted(out)


def _pack_for_sources(
    sources: list[str], packs: dict[str, VendorPack]
) -> VendorPack | None:
    """The pack for the product that emitted this value, if it is recognised."""
    for s in sources:
        vendor, _, product = s.partition(" / ")
        pack = match_pack(vendor.strip(), product.strip(), packs)
        if pack:
            return pack
    return None


def _normalising_pack(
    sources: list[str], packs: dict[str, VendorPack]
) -> VendorPack | None:
    """The pack whose alert_name knowledge applies to this value.

    Prefers the exact product's pack. Falls back to a SIBLING pack from the same
    vendor when the exact pack carries no normalisation knowledge — Check Point
    emits the same ``dga-*.TC.*`` tokens under both ``SmartDefense`` and
    ``Check Point NGFW``, and only the SmartDefense pack documents them. On a
    live tenant that fallback moved 132 values from "unrelated" to the truthful
    "machine-generated".

    ``match_pack`` deliberately refuses a vendor-level fallback because a wrong
    pack supplies a wrong role, taxonomy and identity field. Nothing of the sort
    happens here: the only thing borrowed is a noise/normalisation regex, and a
    regex that does not match changes nothing. The failure mode is bounded to
    withholding, never to proposing.
    """
    own = _pack_for_sources(sources, packs)
    if own and (own.alert_name_pattern or own.alert_name_noise):
        return own

    if own:
        vendors = {own.vendor.lower()}
    else:
        vendors = {s.partition(" / ")[0].strip().lower() for s in sources if s}
    for pack in packs.values():
        if pack.vendor.lower() in vendors and (
            pack.alert_name_pattern or pack.alert_name_noise
        ):
            return pack
    return own


def is_per_record(value: str) -> bool:
    """Whether a value was built per event rather than per policy.

    Such a value can never be matched by an exact-match context table, and on a
    DLP feed it carries the message subject — which is customer content.
    """
    v = (value or "").strip()
    return len(v) > _MAX_ENTRY_CHARS or bool(_PER_RECORD.search(v))


def _redact(
    *,
    value: str,
    field_name: str,
    decision: str,
    reason: str,
    normalised: bool,
    include_withheld: bool,
) -> bool:
    """Whether this value's text must be kept out of the output file."""
    if decision == PROPOSE:
        # Proposals are per-record-rejected before they get here.
        return False
    if reason == REASON_HIGH_CARDINALITY:
        # Only the vendor-recovered policy name is safe; the raw string is the
        # thing carrying the subject line.
        return not normalised
    if is_per_record(value):
        # Field type is not a safety guarantee. A misparse put
        # `<creds><USR>firstname.lastname@<customer>.org<...` into `web_domain`
        # on a live tenant — a structured taxonomy field carrying a raw log
        # fragment with a named person in it. The content test has to run on
        # every field, not only on the ones known to be free text.
        return True
    if reason == REASON_MACHINE_GENERATED:
        return False
    return field_name == "alert_name" and not include_withheld


# --- classification ----------------------------------------------------------


@dataclass
class _Decision:
    """One raw live value, decided. Aggregated into GapValue afterwards."""

    raw: str
    value: str
    decision: str
    reason: str
    normalised: bool = False
    sources: list[str] = field(default_factory=list)
    detail: str = ""


def _classify_alert_names(
    v: TableValidation,
    profile: TenantProfile,
    packs: dict[str, VendorPack],
) -> list[_Decision]:
    """Normalise, then decide, every missing ``alert_name`` value.

    Normalisation runs FIRST and per vendor. Diffing raw values here compares
    thousands of one-shot strings and proposes adding all of them.
    """
    grouped: dict[str, list[str]] = {}
    pack_by_key: dict[str, VendorPack | None] = {}
    for raw in v.missing:
        pack = _normalising_pack(_sources(profile, v.fields, raw), packs)
        key = pack.key if pack else ""
        grouped.setdefault(key, []).append(raw)
        pack_by_key[key] = pack

    entries = set(v.entries)
    out: list[_Decision] = []
    for key, raws in grouped.items():
        pack = pack_by_key[key]
        # The distinct-value list is discarded: every decision is needed, and
        # the second return value is exactly the per-value audit trail.
        _diffable, decisions = normalise_alert_names(raws, pack)
        for raw, decision in zip(raws, decisions, strict=True):
            out.append(_decide_alert(raw, decision, pack, v, profile, entries))
    return out


def _decide_alert(
    raw: str,
    norm: Normalised,
    pack: VendorPack | None,
    v: TableValidation,
    profile: TenantProfile,
    entries: set[str],
) -> _Decision:
    value = (norm.value or raw).strip()
    sources = _sources(profile, v.fields, raw)
    templates = {t.lower() for t in pack.alert_name_templates} if pack else set()
    ai = is_ai_alert_name(value) or value.lower() in templates

    def make(decision: str, reason: str, detail: str = "") -> _Decision:
        return _Decision(
            raw=raw,
            value=value,
            decision=decision,
            reason=reason,
            normalised=norm.rewritten,
            sources=sources,
            detail=detail,
        )

    if norm.is_noise:
        # A vendor noise pattern is a strong prior, not a verdict. Palo Alto's
        # `Grayware:`/`Parked:` prefixes are domain verdicts and mostly noise —
        # but `Parked:broadstreet.ai` is a parked AI-branded domain, which is
        # precisely the shadow-AI signal this whole exercise exists to surface.
        if _STRONG_AI.search(value) and not is_per_record(value):
            return make(
                PROPOSE,
                REASON_AI_OVER_NOISE,
                f"{pack.product if pack else 'vendor'} pack treats this prefix as "
                "noise; this value carries an AI signal",
            )
        return make(
            WITHHOLD,
            REASON_MACHINE_GENERATED,
            norm.reason or "matched a vendor noise pattern",
        )

    if norm.rewritten:
        # The RAW was a per-record wrapper — one distinct string per email, with
        # the subject inside it. Only the recovered policy name may be reported,
        # and only an AI policy may be proposed. This is the branch that turned
        # 3,573 live values into 2 lines of output.
        if ai and not is_per_record(value) and value.lower() not in entries:
            return make(
                PROPOSE,
                REASON_AI_POLICY,
                f"policy name recovered from the {pack.product if pack else 'vendor'}"
                " per-record wrapper",
            )
        return make(
            WITHHOLD,
            REASON_HIGH_CARDINALITY,
            f"{pack.product if pack else 'vendor'} wraps this policy per record; "
            "the raw value is never matchable and carries message content",
        )

    if value.lower() in entries:
        return make(
            WITHHOLD,
            REASON_ALREADY_COVERED,
            "table already holds this value",
        )

    if is_per_record(raw) or is_per_record(value):
        # Per-record shape with nothing to normalise it — no pack, or a shape the
        # pack's pattern does not cover. Withholding is the only safe answer: the
        # value cannot match, and it carries content.
        return make(
            WITHHOLD,
            REASON_HIGH_CARDINALITY,
            "per-record or over-long value: never matchable as a table entry",
        )

    if not ai:
        return make(WITHHOLD, REASON_NOT_AI, "no AI/LLM signal in the value")

    if value.lower() in templates:
        return make(PROPOSE, REASON_VENDOR_TEMPLATE, "known template for this product")
    return make(PROPOSE, REASON_AI_CLASSIFIED, "AI/LLM signal in the value")


def _classify_plain(
    v: TableValidation,
    profile: TenantProfile,
    kind: str,
    ctx: dict[str, Any],
) -> list[_Decision]:
    """Decide missing values for the non-alert_name tables.

    Domains and categories reuse the discovery buckets wholesale rather than
    re-deriving them — two commands disagreeing about the same tenant is the one
    failure mode nobody can debug from the output.
    """
    entries = set(v.entries)
    out: list[_Decision] = []
    for raw in v.missing:
        value = raw.strip()
        sources = _sources(profile, v.fields, raw)
        if is_per_record(value):
            # Applies to every field, not only alert_name: a misparse can put a
            # raw log fragment into any of them, and such a value is unmatchable
            # as a table entry regardless of what it contains.
            decision, reason, detail = (
                WITHHOLD,
                REASON_HIGH_CARDINALITY,
                "per-record or over-long value: never matchable as a table entry",
            )
        else:
            decision, reason, detail = _decide_plain(value, kind, ctx)
        if decision == PROPOSE and value.lower() in entries:
            decision, reason, detail = (
                WITHHOLD,
                REASON_ALREADY_COVERED,
                "table already holds this value",
            )
        out.append(
            _Decision(
                raw=raw,
                value=value,
                decision=decision,
                reason=reason,
                sources=sources,
                detail=detail,
            )
        )
    return out


def _decide_plain(value: str, kind: str, ctx: dict[str, Any]) -> tuple[str, str, str]:
    low = value.lower()

    if kind == "domain":
        classified: dict[str, tuple[str, str]] = ctx["domains"]
        bucket, why = classified.get(low, ("", ""))
        if bucket == KNOWN:
            return PROPOSE, REASON_REFERENCE, why
        if bucket == EXCLUDED:
            return WITHHOLD, REASON_EXCLUDED_MARTECH, why
        if bucket == CANDIDATE:
            return WITHHOLD, REASON_NEEDS_REVIEW, why
        return WITHHOLD, REASON_NOT_AI, "not an AI domain by reference or pattern"

    if kind == "category":
        if low in ctx["ai_categories"]:
            return PROPOSE, REASON_AI_CATEGORY, "discovery classified this as AI"
        if low in ctx["pack_categories"]:
            return PROPOSE, REASON_VENDOR_CATEGORY, "declared by a vendor pack"
        return WITHHOLD, REASON_NOT_AI, "not an AI category"

    if kind == "app":
        if low in ctx["reference_apps"]:
            return PROPOSE, REASON_REFERENCE, "in bundled AI application data"
        if has_ai_provider_token(value):
            return PROPOSE, REASON_AI_CLASSIFIED, "names a known AI provider"
        if has_weak_ai_hint(value) or is_ai_alert_name(value):
            return WITHHOLD, REASON_NEEDS_REVIEW, "weak AI signal only"
        return WITHHOLD, REASON_NOT_AI, "no AI signal"

    if kind == "process":
        if _AI_PROCESS.search(value):
            return PROPOSE, REASON_AI_PROCESS, "known local model runtime or AI tool"
        if _DEV_PROCESS.match(value):
            return (
                WITHHOLD,
                REASON_NEEDS_REVIEW,
                "interpreter or package manager: runs AI frameworks, but also "
                "runs everything else",
            )
        return WITHHOLD, REASON_NOT_AI, "not an AI process"

    return WITHHOLD, REASON_NEEDS_REVIEW, f"no classifier for field kind {kind!r}"


def _aggregate(
    table_name: str,
    field_name: str,
    decisions: list[_Decision],
    *,
    include_withheld: bool,
) -> tuple[list[GapValue], list[GapValue]]:
    """Collapse per-value decisions into reported entries, preserving counts."""
    merged: dict[tuple[str, str, str | None], GapValue] = {}
    order: list[tuple[str, str, str | None]] = []

    for d in decisions:
        redacted = _redact(
            value=d.value,
            field_name=field_name,
            decision=d.decision,
            reason=d.reason,
            normalised=d.normalised,
            include_withheld=include_withheld,
        )
        shown = None if redacted else d.value
        key = (d.decision, d.reason, shown if shown is not None else "")
        existing = merged.get(key)
        if existing is None:
            merged[key] = GapValue(
                value=shown,
                table=table_name,
                field_name=field_name,
                decision=d.decision,
                reason=d.reason,
                raw_count=1,
                normalised=d.normalised,
                redacted=redacted,
                sources=list(d.sources),
                detail=d.detail,
            )
            order.append(key)
            continue
        existing.raw_count += 1
        existing.normalised = existing.normalised or d.normalised
        for s in d.sources:
            if s not in existing.sources:
                existing.sources.append(s)

    propose: list[GapValue] = []
    withhold: list[GapValue] = []
    for key in order:
        g = merged[key]
        g.sources.sort()
        (propose if g.decision == PROPOSE else withhold).append(g)

    propose.sort(key=lambda g: (g.value or "").lower())
    withhold.sort(key=lambda g: (-g.raw_count, g.reason, (g.value or "")))
    return propose, withhold


def build_gap_report(
    validations: list[TableValidation],
    profile: TenantProfile,
    *,
    packs: dict[str, VendorPack] | None = None,
    include_withheld_values: bool = False,
) -> GapReport:
    """Classify every missing value. Pure — no API calls, no writes.

    Args:
        validations: Output of ``validate_aillm_tables``.
        profile: The profile those validations were measured against.
        packs: Vendor packs. Loaded from the bundled data when omitted.
        include_withheld_values: Write withheld ``alert_name`` text to the
            report. Off by default: those strings are free text authored by the
            source product and carry customer content on DLP feeds.

    Returns:
        GapReport. Every examined value appears in exactly one bucket, which
        ``GapReport.balanced`` asserts.
    """
    packs = load_vendor_packs() if packs is None else packs

    domain_buckets: dict[str, tuple[str, str]] = {}
    discovery = discover_ai_domains(None, profile=profile)  # type: ignore[arg-type]
    for bucket, items in (
        (KNOWN, discovery.known),
        (CANDIDATE, discovery.candidates),
        (EXCLUDED, discovery.excluded),
    ):
        for d in items:
            domain_buckets[d.domain.lower()] = (bucket, d.reason)

    ctx: dict[str, Any] = {
        "domains": domain_buckets,
        "ai_categories": {
            c.value.lower()
            for c in discover_categories(None, profile=profile)  # type: ignore[arg-type]
        },
        "pack_categories": known_ai_categories(packs),
        "reference_apps": _reference_apps(),
    }

    report = GapReport(
        tenant=profile.tenant,
        collected_at=profile.collected_at,
        lookback_days=profile.lookback_days,
        api_calls=profile.api_calls,
        truncated_fields=sorted(
            {
                f
                for spec in TABLE_SPECS.values()
                for f in spec.fields
                if profile.truncated(f)
            }
        ),
    )

    for v in validations:
        kind = _KIND_BY_FIELD.get(v.fields[0] if v.fields else "", "")
        tg = TableGaps(
            table_name=v.table_name,
            fields=list(v.fields),
            table_id=v.table_id,
            key_attr=v.key_attr,
            status=v.status,
            records=v.records,
            consumers=list(v.consumers),
            read_by_rules=v.read_by_rules,
            truncated_sample=v.truncated_sample,
            note=v.note,
            examined=len(v.missing),
        )
        if v.missing:
            if kind == "alert_name":
                decisions = _classify_alert_names(v, profile, packs)
            else:
                decisions = _classify_plain(v, profile, kind, ctx)
            tg.propose, tg.withhold = _aggregate(
                v.table_name,
                v.fields[0] if v.fields else "",
                decisions,
                include_withheld=include_withheld_values,
            )
        report.tables.append(tg)

    return report


def _reference_apps() -> set[str]:
    from exa.aillm.reference import load_reference_data

    return {str(r.get("key", "")).lower() for r in load_reference_data().applications}


def deepen_truncated_fields(
    client: ExaClient,
    profile: TenantProfile,
    *,
    limit: int = _DEEP_LIMIT,
    fields: list[str] | None = None,
) -> list[str]:
    """Re-enumerate capped fields at a higher row cap. READ-ONLY.

    Why this is not optional in practice
    ------------------------------------
    The standing profile caps each enumeration at 5,000 rows, and the cap is not
    a random sample you can reason about — it is truncated *and* non-deterministic
    between runs. On a live healthcare tenant ``alert_name`` has **27,781**
    distinct values, of which 3,573-plus are Microsoft Purview per-email strings.
    The 5,000-row sample was so dominated by that noise that six of the eight
    genuine AI alert names never appeared at all. A gap report built on it says
    "2 proposals" with total confidence and is wrong by a factor of four.

    Filtering instead of enumerating does not work here and fails silently: with
    ``groupBy`` set, this tenant IGNORES the EQL query entirely — an exact-match
    ``alert_name:"AIEnterpriseInteractionsExported"`` returned 200 unrelated
    values rather than an error. A bigger cap is the only reliable answer.

    Costs one API call per truncated field, and re-caches so the next command
    inherits the better sample. Truncation is re-recorded, never assumed cleared:
    a field still capped at the higher limit stays a lower bound.

    Returns:
        The field names that were re-enumerated.
    """
    from exa.search.events import search_events

    wanted = fields or sorted(
        {f for spec in TABLE_SPECS.values() for f in spec.fields}
    )
    deepened: list[str] = []
    for name in wanted:
        if not profile.truncated(name):
            continue
        combo = [name, "product", "vendor"]
        try:
            rows = search_events(
                client,
                "",
                fields=combo,
                lookback_days=profile.lookback_days,
                limit=limit,
                group_by=combo,
            )
            profile.api_calls += 1
        except Exception:  # noqa: BLE001 - a failed deepening keeps the old sample
            profile.api_calls += 1
            continue

        values: set[str] = set()
        attribution: dict[str, set[str]] = {}
        for row in rows:
            val = str(row.get(name) or "").strip()
            if not val or val == "None":
                continue
            values.add(val)
            vendor = str(row.get("vendor") or "").strip()
            product = str(row.get("product") or "").strip()
            if product and product != "None":
                label = (
                    f"{vendor} / {product}"
                    if vendor and vendor != "None"
                    else product
                )
                attribution.setdefault(val, set()).add(label)

        profile.fields[name] = FieldValues(
            field_name=name,
            values=sorted(values),
            truncated=len(rows) >= limit,
        )
        if attribution:
            profile.attribution[name] = {k: sorted(v) for k, v in attribution.items()}
        deepened.append(name)

    if deepened:
        save_profile(profile)
    return deepened


def analyze_gaps(
    client: ExaClient,
    *,
    profile: TenantProfile | None = None,
    lookback_days: int = 30,
    refresh: bool = False,
    include_withheld_values: bool = False,
    deep: bool = True,
) -> GapReport:
    """Measure and classify the gap between live values and each context table.

    Read-only: a profile collection (cached, usually free), one re-enumeration
    per truncated field when ``deep``, and the table reads ``validate`` already
    performs. Nothing is written to the tenant.
    """
    profile = profile or collect_tenant_profile(
        client, lookback_days=lookback_days, refresh=refresh
    )
    deepened: list[str] = []
    if deep:
        # Probe first so every field the tables are matched against exists in the
        # profile — process_name and parent_process_name are outside the standing
        # enumeration, and an unprobed field cannot be reported as truncated.
        ensure_fields(
            client,
            profile,
            sorted({f for spec in TABLE_SPECS.values() for f in spec.fields}),
        )
        deepened = deepen_truncated_fields(client, profile)

    validations = validate_aillm_tables(client, profile=profile)
    report = build_gap_report(
        validations, profile, include_withheld_values=include_withheld_values
    )
    report.deepened_fields = deepened
    return report


# How many withheld entries to LIST per reason. Counts are always complete; this
# caps the listing only. Uncapped, a tenant with 43,461 withheld web_domain
# values produced a 43 MB "reviewable" file that no reviewer would open — and
# put 43,000 lines of customer traffic on disk to say nothing a count did not.
_MAX_LISTED_PER_REASON = 200


def gap_report_to_dict(
    report: GapReport, *, max_listed_per_reason: int = _MAX_LISTED_PER_REASON
) -> dict[str, Any]:
    """Serialise for the reviewable JSON file.

    Every count is labelled a lower bound when its sample was truncated. A total
    that implies completeness is worse than no total: it retires a question that
    is still open.

    Proposals are always listed in full. Withheld entries are listed up to
    ``max_listed_per_reason`` per reason (0 = no cap), with ``listed`` and
    ``not_listed`` stated per table so the elision is visible rather than
    silent. The counts in ``withheld_by_reason`` are unaffected and complete.
    """
    return {
        "tenant": report.tenant,
        "collected_at": report.collected_at,
        "lookback_days": report.lookback_days,
        "api_calls": report.api_calls,
        "read_only": True,
        "counts_are_lower_bound": report.lower_bound,
        "truncated_fields": report.truncated_fields,
        "deepened_fields": report.deepened_fields,
        "every_value_accounted_for": report.balanced,
        "tables": [
            _table_to_dict(t, max_listed_per_reason) for t in report.tables
        ],
    }


def _table_to_dict(t: TableGaps, max_listed_per_reason: int) -> dict[str, Any]:
    listed = _listed(t, max_listed_per_reason)
    return {
        "table": t.table_name,
        "table_id": t.table_id,
        "key_attr": t.key_attr,
        "fields": t.fields,
        "consumers": t.consumers,
        "read_by_rules": t.read_by_rules,
        "status": t.status,
        "records": t.records,
        "note": t.note,
        "sample_truncated": t.truncated_sample,
        "counts_are_lower_bound": t.truncated_sample,
        "examined": t.examined,
        "proposed": t.proposed,
        "withheld_values": t.withheld_values,
        "withheld_distinct": t.withheld_distinct,
        "withheld_by_reason": t.by_reason(),
        "balanced": t.balanced,
        "propose": [_value_to_dict(g) for g in t.propose],
        "withhold": [_value_to_dict(g) for g in listed],
        "withhold_listing": {
            "max_listed_per_reason": max_listed_per_reason,
            "listed": len(listed),
            "not_listed": t.withheld_distinct - len(listed),
        },
    }


def _listed(table: TableGaps, max_per_reason: int) -> list[GapValue]:
    """Withheld entries to write out, capped per reason. Counts stay complete."""
    if max_per_reason <= 0:
        return table.withhold
    seen: dict[str, int] = {}
    out: list[GapValue] = []
    for g in table.withhold:
        n = seen.get(g.reason, 0)
        if n >= max_per_reason:
            continue
        seen[g.reason] = n + 1
        out.append(g)
    return out


def _value_to_dict(g: GapValue) -> dict[str, Any]:
    return {
        "value": g.value,
        "table": g.table,
        "field": g.field_name,
        "decision": g.decision,
        "reason": g.reason,
        "live_values": g.raw_count,
        "normalised": g.normalised,
        "redacted": g.redacted,
        "sources": g.sources,
        "detail": g.detail,
    }
